version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432"
        ]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  web:
    build: task_service/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # команда на время разработки
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


  rqworker:
    build: task_service/
    command: python manage.py rqworker
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: